### ISSUE TITLE
Crisis_hotlines fails to keep page margins

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-my-content#35]
Field message_text_1::eng in the article crisis_hotlines fails to keep page margins on a mobile device. 

![Screenshot_20231102-145428](https://github.com/IDEMSInternational/plh-facilitator-app-my-content/assets/74552270/fc2de82c-ff5c-490f-a53e-c02141cb4057)

**Comment by esmeetewinkel** [comment]
We're aware of [this issue](https://github.com/IDEMSInternational/parenting-app-ui/issues/2094), but I hadn't realised this was something that needed to be prioritised for the FaciNK release (since we do have messages containing hyperlinks and WhatsApp doesn't support markdown). 

I would suggest to replace these links by markdown hyperlinks for now so that at least the share button is clickable. I will discuss with the dev team tomorrow whether this can be solved asap, but I'm not sure it will be before Monday.

**Comment by esmeetewinkel** [comment]
> I would suggest to replace these links by markdown hyperlinks for now so that at least the share button is clickable. I will discuss with the dev team tomorrow whether this can be solved asap, but I'm not sure it will be before Monday.

This dev issue was resolved this morning, so no need to make any temporary changes to the data list!
