### ISSUE TITLE
Message_text_1 sends "undefined" with message when guidance is blank

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-my-content#36]
Message Text 1 field is sent with the text "undefined" at the end of the message. This doesn't seem to happen to Text 2 and 3. 

![Screenshot_20231102-145906](https://github.com/IDEMSInternational/plh-facilitator-app-my-content/assets/74552270/c7ddb55a-c322-4340-bf99-797218b164dc)

**Comment by esmeetewinkel** [comment]
Thanks for flagging! Turns out this "undefined" on Message 1 dated back from when we said the first message should contain a message disclaimer. But it seems that we've gotten rid of the message disclaimer text since then, and so that's now showing as undefined. I've fixed this, adding a condition to not show anything when the message disclaimer text is not defined. 

<img width="359" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-my-content/assets/74557272/73b02550-32ae-41f9-a517-f126e72cef5f">

Closed by https://github.com/IDEMSInternational/plh-facilitator-app-my-content/pull/38

 (let me know if we *do* need to re-insert the disclaimer, and what you would like the text to be)
