### ISSUE TITLE
Submitting Reporting form Takes User to the Wrong Screen

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/plh-facilitator-app-my-content#45]
**To Recreate** Select the Pencil, complete a reporting form, select "Submit" 
https://github.com/IDEMSInternational/parenttext-malaysia/issues/7

After selecting the SUBMIT the user should be brought back to the main reporting screen. Instead, the user is prompted to submit another report that fits within the parent category (in-person, WhatsApp). If the user has already submitted all available forms, they receive an error when they haven't attempted an error.

**Comment by esmeetewinkel** [comment]
This bug (returning to the pop-up rather than the underlying screen) is a dev issue, flagged in https://github.com/IDEMSInternational/parenting-app-ui/issues/2120.

In the mean time: When a user has submitted all in-person form, they are seeing
<img width="242" alt="image" src="https://github.com/IDEMSInternational/plh-facilitator-app-my-content/assets/74557272/e151a0d2-4b77-4665-bf39-fb66a95b2c7b">
I will insert a similar phrase in the pop-up for WhatsApp forms, sorry for missing that. 

If that is not the error you mean, could you send a screenshot of the error?
