### ISSUE TITLE
FaciNK iOS release

### ISSUE THREAD

**Issue by esmeetewinkel** [IDEMSInternational/plh-facilitator-app-my-content#79]
For the Scale Up we will need an iOS release of FacilitatorApp Malaysia

**Comment by lauriemarkle** [comment]
@esmeetewinkel We will need to update the Facilitator Manuals to direct users to the App Store rather than web preview and translate any changes made to the manual (and upload the updated manual to the Facilitator App!) before the milestone. Therefore, can you please have this live before 28 May 2024?

**Comment by esmeetewinkel** [comment]
Released to App Store on 22 May 2024. Listing: https://apps.apple.com/us/app/facink/id6502831837
